In [2]:
import pandas as pd
import numpy as np
import itertools
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer, HashingVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import PassiveAggressiveClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn import metrics
import matplotlib.pyplot as plt

In [3]:
df=pd.read_csv('news.csv', index_col=None)

In [4]:
df

,Unnamed: 0,title,text,label
0,8476,You Can Smell Hillary’s Fear,"Daniel Greenfield, a Shillman Journalism Fello...",FAKE
1,10294,Watch The Exact Moment Paul Ryan Committed Pol...,Google Pinterest Digg Linkedin Reddit Stumbleu...,FAKE
2,3608,Kerry to go to Paris in gesture of sympathy,U.S. Secretary of State John F. Kerry said Mon...,REAL
3,10142,Bernie supporters on Twitter erupt in anger ag...,"— Kaydee King (@KaydeeKing) November 9, 2016 T...",FAKE
4,875,The Battle of New York: Why This Primary Matters,It's primary day in New York and front-runners...,REAL
...,...,...,...,...
6330,4490,State Department says it can't find emails fro...,The State Department told the Republican Natio...,REAL
6331,8062,The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...,The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...,FAKE
6332,8622,Anti-Trump Protesters Are Tools of the Oligarc...,Anti-Trump Protesters Are Tools of the Oligar...,FAKE
6333,4021,"In Ethiopia, Obama seeks progress on peace, se...","ADDIS ABABA, Ethiopia —President Obama convene...",REAL


In [5]:
dataset=df.drop("Unnamed: 0",axis=1)

In [6]:
dataset

,title,text,label
0,You Can Smell Hillary’s Fear,"Daniel Greenfield, a Shillman Journalism Fello...",FAKE
1,Watch The Exact Moment Paul Ryan Committed Pol...,Google Pinterest Digg Linkedin Reddit Stumbleu...,FAKE
2,Kerry to go to Paris in gesture of sympathy,U.S. Secretary of State John F. Kerry said Mon...,REAL
3,Bernie supporters on Twitter erupt in anger ag...,"— Kaydee King (@KaydeeKing) November 9, 2016 T...",FAKE
4,The Battle of New York: Why This Primary Matters,It's primary day in New York and front-runners...,REAL
...,...,...,...
6330,State Department says it can't find emails fro...,The State Department told the Republican Natio...,REAL
6331,The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...,The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...,FAKE
6332,Anti-Trump Protesters Are Tools of the Oligarc...,Anti-Trump Protesters Are Tools of the Oligar...,FAKE
6333,"In Ethiopia, Obama seeks progress on peace, se...","ADDIS ABABA, Ethiopia —President Obama convene...",REAL


In [7]:
y=dataset["label"]

In [8]:
X_train, X_test, y_train, y_test = train_test_split(dataset['text'], y, test_size=0.33, random_state=53)

In [9]:
count_vectorizer = CountVectorizer(stop_words='english')
count_train = count_vectorizer.fit_transform(X_train)
print(count_train)
count_test = count_vectorizer.transform(X_test)

  (1, 42470)	1
  (1, 12105)	1
  (1, 54177)	1
  (1, 50628)	1
  (1, 15924)	2
  (1, 44520)	2
  (1, 51896)	2
  (1, 35783)	4
  (1, 35256)	1
  (1, 21881)	1
  (1, 42534)	1
  (1, 8399)	1
  (1, 29531)	2
  (1, 15927)	2
  (1, 25686)	1
  (1, 49203)	2
  (1, 16814)	1
  (1, 36087)	1
  (1, 21568)	1
  (1, 25684)	1
  (1, 38823)	1
  (1, 47506)	1
  (1, 36831)	1
  (2, 16972)	1
  (2, 762)	1
  :	:
  (4243, 41435)	1
  (4243, 53607)	1
  (4243, 659)	1
  (4243, 38834)	1
  (4243, 19003)	1
  (4243, 11415)	1
  (4243, 7545)	1
  (4243, 22426)	1
  (4243, 54007)	1
  (4243, 7113)	1
  (4243, 4932)	1
  (4243, 39497)	1
  (4243, 50053)	1
  (4243, 38849)	1
  (4243, 20702)	1
  (4243, 42139)	1
  (4243, 17247)	1
  (4243, 50052)	1
  (4243, 55228)	1
  (4243, 29255)	1
  (4243, 49435)	1
  (4243, 11257)	1
  (4243, 52945)	1
  (4243, 20905)	1
  (4243, 7962)	1


In [10]:
print(count_train.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [11]:
clf = MultinomialNB()

clf.fit(count_train, y_train)
pred = clf.predict(count_test)
score = metrics.accuracy_score(y_test, pred)
print("accuracy:   %0.3f" % score)

cm = metrics.confusion_matrix(y_test, pred, labels=['FAKE', 'REAL'])

accuracy:   0.893


In [12]:
from sklearn.metrics import classification_report

report=classification_report(y_test, pred)

In [13]:
print(report)

              precision    recall  f1-score   support

        FAKE       0.92      0.86      0.89      1008
        REAL       0.88      0.93      0.90      1083

    accuracy                           0.89      2091
   macro avg       0.90      0.89      0.89      2091
weighted avg       0.89      0.89      0.89      2091



In [14]:
#To get the first line from the dataset
dataset["text"][0]

'Daniel Greenfield, a Shillman Journalism Fellow at the Freedom Center, is a New York writer focusing on radical Islam. \nIn the final stretch of the election, Hillary Rodham Clinton has gone to war with the FBI. \nThe word “unprecedented” has been thrown around so often this election that it ought to be retired. But it’s still unprecedented for the nominee of a major political party to go war with the FBI. \nBut that’s exactly what Hillary and her people have done. Coma patients just waking up now and watching an hour of CNN from their hospital beds would assume that FBI Director James Comey is Hillary’s opponent in this election. \nThe FBI is under attack by everyone from Obama to CNN. Hillary’s people have circulated a letter attacking Comey. There are currently more media hit pieces lambasting him than targeting Trump. It wouldn’t be too surprising if the Clintons or their allies were to start running attack ads against the FBI. \nThe FBI’s leadership is being warned that the entir

In [28]:
#To get the count train of first row
count_train[[20]]

<1x56922 sparse matrix of type '<class 'numpy.int64'>'
	with 220 stored elements in Compressed Sparse Row format>

In [17]:
# Assume count train as separate file this is deployment phase(as different file)
count_vectorizer = CountVectorizer(stop_words='english')
count_train = count_vectorizer.fit_transform(X_train)

In [26]:
X_train[[20]]

20    With little fanfare this fall, the New York de...
Name: text, dtype: object

In [27]:
clf.predict(count_train[[20]])

array(['REAL'], dtype='<U4')

# Doing with different classification Algorithm with counter vector
# Random Forest

In [11]:
from sklearn.ensemble import RandomForestClassifier
Classifier=RandomForestClassifier(n_estimators=10,criterion='entropy',random_state=0)
Classifier.fit(count_train,y_train)

C:\Anaconda\envs\dataai\lib\site-packages\sklearn\utils\fixes.py:230: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if _joblib.__version__ >= LooseVersion('0.12'):


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [12]:
y_pred=Classifier.predict(count_test)

C:\Anaconda\envs\dataai\lib\site-packages\sklearn\utils\fixes.py:230: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if _joblib.__version__ >= LooseVersion('0.12'):


In [15]:
score1 = metrics.accuracy_score(y_test, y_pred)
print("accuracy:   %0.3f" % score1)

accuracy:   0.842


In [14]:
from sklearn.metrics import confusion_matrix
cm_rf = confusion_matrix(y_test,y_pred, labels=['FAKE', 'REAL'])

In [17]:
print(cm_rf)

[[911  97]
 [234 849]]


In [18]:
from sklearn.metrics import classification_report
clrf_report=classification_report(y_test,y_pred)

In [19]:
print(clrf_report)

              precision    recall  f1-score   support

        FAKE       0.80      0.90      0.85      1008
        REAL       0.90      0.78      0.84      1083

    accuracy                           0.84      2091
   macro avg       0.85      0.84      0.84      2091
weighted avg       0.85      0.84      0.84      2091



# Decision Tree Classification

In [20]:
from sklearn.tree import DecisionTreeClassifier
classifierd = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifierd.fit(count_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=0, splitter='best')

In [21]:
y_predd=classifierd.predict(count_test)

In [22]:
score2 = metrics.accuracy_score(y_test, y_predd)
print("accuracy:   %0.3f" % score2)

accuracy:   0.820


In [23]:
from sklearn.metrics import confusion_matrix
cm_dt = confusion_matrix(y_test,y_predd, labels=['FAKE', 'REAL'])

In [24]:
print(cm_dt)

[[826 182]
 [195 888]]


In [25]:
from sklearn.metrics import classification_report
cldt_report=classification_report(y_test,y_predd)

In [26]:
print(cldt_report)

              precision    recall  f1-score   support

        FAKE       0.81      0.82      0.81      1008
        REAL       0.83      0.82      0.82      1083

    accuracy                           0.82      2091
   macro avg       0.82      0.82      0.82      2091
weighted avg       0.82      0.82      0.82      2091



# Support Vector Machine Classification

In [27]:
from sklearn.svm import SVC
classifiersvm = SVC(kernel = 'rbf', random_state = 0)
classifiersvm.fit(count_train, y_train)

C:\Anaconda\envs\dataai\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=0,
    shrinking=True, tol=0.001, verbose=False)

In [28]:
y_predsv=classifiersvm.predict(count_test)

In [29]:
score3 = metrics.accuracy_score(y_test,y_predsv)
print("accuracy:   %0.3f" % score3)

accuracy:   0.741


In [30]:
cm_svm = confusion_matrix(y_test,y_predsv, labels=['FAKE', 'REAL'])

In [31]:
print(cm_svm)

[[974  34]
 [508 575]]


In [32]:
clsvm_report=classification_report(y_test,y_predsv)

In [33]:
print(clsvm_report)

              precision    recall  f1-score   support

        FAKE       0.66      0.97      0.78      1008
        REAL       0.94      0.53      0.68      1083

    accuracy                           0.74      2091
   macro avg       0.80      0.75      0.73      2091
weighted avg       0.81      0.74      0.73      2091



# Logistic classification

In [34]:
from sklearn.linear_model import LogisticRegression
classifierl=LogisticRegression(random_state=0)
classifierl.fit(count_train, y_train)

C:\Anaconda\envs\dataai\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=0, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [35]:
y_predl=classifierl.predict(count_test)

In [36]:
score4 = metrics.accuracy_score(y_test,y_predl)
print("accuracy:   %0.3f" % score4)

accuracy:   0.910


In [37]:
cm_lc = confusion_matrix(y_test,y_predl, labels=['FAKE', 'REAL'])

In [38]:
print(cm_lc)

[[947  61]
 [128 955]]


In [39]:
cllc_report=classification_report(y_test,y_predl)

In [40]:
print(cllc_report)

              precision    recall  f1-score   support

        FAKE       0.88      0.94      0.91      1008
        REAL       0.94      0.88      0.91      1083

    accuracy                           0.91      2091
   macro avg       0.91      0.91      0.91      2091
weighted avg       0.91      0.91      0.91      2091



# KNeighbour Classification

In [41]:
from sklearn.neighbors import KNeighborsClassifier
classifierknn = KNeighborsClassifier(n_neighbors = 7, metric = 'minkowski', p = 2)
classifierknn.fit(count_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=7, p=2,
                     weights='uniform')

In [42]:
y_predkn=classifierknn.predict(count_test)

In [43]:
score5 = metrics.accuracy_score(y_test,y_predkn)
print("accuracy:   %0.3f" % score5)

accuracy:   0.786


In [44]:
cm_kn = confusion_matrix(y_test,y_predkn, labels=['FAKE', 'REAL'])

In [45]:
print(cm_kn)

[[835 173]
 [275 808]]


In [46]:
clkn_report=classification_report(y_test,y_predkn)

In [48]:
print(clkn_report)

              precision    recall  f1-score   support

        FAKE       0.75      0.83      0.79      1008
        REAL       0.82      0.75      0.78      1083

    accuracy                           0.79      2091
   macro avg       0.79      0.79      0.79      2091
weighted avg       0.79      0.79      0.79      2091



# Logistic Classification is the best model comparing the other 6 models(KNN,Navie Bayes,SVM,Decision Tree,Random Forest)